import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="text-center font-sans font-semibold text-2xl">Hello Tailwind</div>
      </main>

      <footer className={styles.footer}>
        <p className="text-center font-serif font-bold text-xs">elemoh 2021</p>
      </footer>
    </div>
  )
}
